use rentals;

DELIMITER //
CREATE PROCEDURE CreateNewUser(IN id int, 
	in Uname varchar(30),
    in AGE INT,
    IN EMAIL VARCHAR(50),
    IN PASSWORD_U VARCHAR(20),
    IN HOUSE INT,
    IN PLOT VARCHAR(20),
    IN STRRT VARCHAR(30),
    IN CITY_U VARCHAR(20),
    IN STATE_U VARCHAR(20),
    IN PINCODE INT
    )
BEGIN
INSERT INTO USERS(ADHAR_ID,
    NAME_USER,
    AGE_USER,
    EMAIL_USER,
    PASSWORD_USER,
    H_No ,
    PLOTNo_USER,
    STREET_USER,
    CITY_USER,
    STATE_USER,
    PINCODE_USER) VALUES(ID, UNAME, AGE, EMAIL, PASSWORD_U, HOUSE, PLOT, STRRT,CITY_U,STATE_U,PINCODE);
    CREATE USER 'EMAIL' IDENTIFIED BY 'PASSWORD_U';
END//
DELIMITER ;
--DROP PROCEDURE CREATENEWUSER;
CALL CREATENEWUSER(0987,'MOHAN', 32,'MO@EMAIL.COM', 'WORDPASS', 12,'12-/322/31', 'BALAJINAGAR', 'DELHI','DELHI', 100020);