USE RENTALS;

DELIMITER //
CREATE PROCEDURE InsertPropertyRecord(IN PROPERTY_ID INT ,
    IN OWNER_ID INT,
    IN RENT INT,
    IN HIKE DECIMAL(5,2),
    IN TOTAL_AREA INT,
    IN PLINTH_AREA INT,
    IN AVAILABLE_FROM DATE,
    IN AVAILABLE_TILL DATE,
    IN CONSTRUCTION_YEAR INT,
    IN H_NO INT,
    IN PLOTNo_PROPERTY VARCHAR(20),
    IN STREET_PROPERTY VARCHAR(50),
    IN CITY_PROPERTY VARCHAR(20),
    IN STATE_PROPERTY VARCHAR(20),
    IN PINCODE_PROPERTY INT,
    IN ISCOMMERCIAL BOOL,
    IN ISRESIDENTIAL BOOL,
    IN FLOOR INT,
    IN BEDROOMS INT,
    IN MANAGER_ID INT)
    BEGIN
    INSERT INTO PROPERTY(PROPERTY_ID,
    OWNER_ID,
    RENT,
    HIKE,
    TOTAL_AREA,
    PLINTH_AREA ,
    AVAILABLE_FROM,
    AVAILABLE_TILL,
    CONSTRUCTION_YEAR,
    H_NO,
    PLOTNo_PROPERTY,
    STREET_PROPERTY,
    CITY_PROPERTY,
    STATE_PROPERTY ,
    PINCODE_PROPERTY,
    ISCOMMERCIAL,
    ISRESIDENTIAL,
    FLOOR,
    BEDROOMS ,
    MANAGER_ID ) 
    VALUES(PROPERTY_ID,
    OWNER_ID,
    RENT,
    HIKE,
    TOTAL_AREA,
    PLINTH_AREA ,
    AVAILABLE_FROM,
    AVAILABLE_TILL,
    CONSTRUCTION_YEAR,
    H_NO,
    PLOTNo_PROPERTY,
    STREET_PROPERTY,
    CITY_PROPERTY,
    STATE_PROPERTY ,
    PINCODE_PROPERTY,
    ISCOMMERCIAL,
    ISRESIDENTIAL,
    FLOOR,
    BEDROOMS ,
    MANAGER_ID);
    END//
DELIMITER ;

CALL INSERTPROPERTYRECORD(4321,2023,1000,10.20,2000,1500,'2023-01-01','2024-01-01',2021,11,'11-12/232','SPRING FIELD','HYD','TELANAGANA',50067,1,0,4,3,1101);

DELIMITER //
CREATE PROCEDURE GetPropertyRecords(IN OWNERID INT)
BEGIN
SELECT * FROM PROPERTY WHERE OWNERID = PROPERTY.OWNER_ID;
END//
DELIMITER ;
CALL GETPROPERTYRECORDS();

DELIMITER //
CREATE PROCEDURE GetTenantDetails(IN PROP_ID INT)
BEGIN
SELECT U.ADHAR_ID ,
    U.NAME_USER,
    U.AGE_USER,
    U.EMAIL_USER,
    U.H_No,
    U.PLOTNo_USER,
    U.STREET_USER,
    U.CITY_USER,
    U.STATE_USER,
    U.PINCODE_USER, 
    ph.phone_1
    FROM users u, property p, phoneno_user ph
    where P.PROPERTY_ID=prop_id AND P.OWNER_ID = U.ADHAR_ID and ph.ADHAR_ID=u.ADHAR_ID;
END //
DELIMITER ;
DROP PROCEDURE GETTENANTDETAILS;

CALL GETTENANTDETAILS(4321);

DELIMITER //
CREATE PROCEDURE SearchPropertyForRent(IN LOCALITY VARCHAR(20))
BEGIN
SELECT * FROM PROPERTY WHERE (LOCALITY LIKE PROPERTY.CITY_PROPERTY OR PROPERTY.STATE_PROPERTY) and curdate() between property.AVAILABLE_FROM and property.AVAILABLE_TILL;
END //
DELIMITER ;

--drop procedure SEARCHPROPERTYFORRENT;
CALL SEARCHPROPERTYFORRENT('HYD');

DELIMITER //
CREATE PROCEDURE GetRentHistory(IN PROPID INT)
BEGIN
SELECT * FROM LOG_BOOK WHERE PROPID = LOG_BOOK.PROPERTY_ID;
END//
DELIMITER ;

CALL GETRENTHISTORY(1022);

create user 'email' identified by 'password';
grant all on dbms_project to 'email';
grant create routine on dbms_project.* to 'email';
grant execute on SEARCHPROPERTYFORRENT to 'email';
grant execute on procedure dbms_project. to 'email';